import type { RagLevel } from '@shared/health';

export type PortfolioTableRow = {
  id: string;
  name: string;
  projectNumber: string;
  category: string;
  risk: string;
  sopTemplateVersion?: string | null;
  customFields?: unknown;
  ragLevel: RagLevel;
  ragReasons: string[];
  customer: string | null;
  currentPhase: string;
  startDate: string | null;
  targetDate: string | null;
  pmUserId: number | null;
  pmName: string | null;
  /** 当前用户对本项目的有效角色（成员角色 ∪ pm/owner/admin 兜底）；用于总览定视角 */
  myRole?: string | null;
  taskTotal: number;
  taskDone: number;
  taskInProgress: number;
  overdueTasks: number;
  blockedTasks: number;
  openIssues: number;
  criticalIssues: number;
  plannedEnd: string | null;
  projectedEnd: string | null;
  progressBehindPct: number | null;
  unassignedTasks: number;
  memberGap: number;
  gateTaskTotal: number;
  gateTaskDone: number;
  gatePhaseId: string | null;
  gateName: string | null;
  gateDueDate: string | null;
  gateDone: boolean;
  gateReady: boolean | null;
  gateBlockers: number;
  gateNotReady: 'red' | 'amber' | null;
  deliverableGap: number;
  releaseDecision: 'approved' | 'conditional' | 'rejected' | null;
  releaseGateName: string | null;
  releaseGateReady: boolean;
  releaseDeliverableDone: number;
  releaseDeliverableTotal: number;
  releaseHardBlockers: number;
  releaseConditions: string | null;
  expenseCurrency?: string | null;
  expenseCurrencyCount?: number;
  expenseBudgetMinor?: number | null;
  expenseActualMinor?: number | null;
  expenseVarianceMinor?: number | null;
};
