// NPD 模板 v3（2026-07-v3）——瘦身分档版。
//
// ⚠️ 复杂度预算（准入纪律，勿删）：核心档 ≤25 任务；核心+常规包组合 ≤30；四包全激活上限 32。
// 任务准入四项判据（至少满足其一，全不满足的职能动作进操作指南/检查项）：
//   ①改变状态 ②明确责任（独立责任人+截止） ③形成决策 ④产生审计证据。
// 过了判据还须回答：为什么不能作为①任务内检查项 ②操作指南 ③附加包？答不上来就不准进核心。
// 55→25 映射依据：docs/superpowers/specs/2026-07-12-npd-template-slimming-tiering-design.md
import type { SOPGateStandard, SOPPhase } from "./sop-templates";

const gateStandard = (overrides: Partial<SOPGateStandard>): SOPGateStandard => ({
  entryCriteria: [],
  exitCriteria: [],
  requiredDeliverables: [],
  responsibleRoles: [],
  evidenceRequirements: [],
  exceptionStrategy: [],
  ...overrides,
});

export const NPD_V3_CORE_PHASES: SOPPhase[] = [
  {
    id: "concept",
    code: "P1",
    name: "概念阶段",
    nameEn: "Concept",
    duration: "2-4周",
    desc: "市场洞察与产品立项",
    gate: "立项评审 / Project Charter",
    gateTaskId: "nc3",
    color: "#78716c",
    deliverables: ["立项申请书", "认证路线图初判"],
    gateStandard: gateStandard({
      exitCriteria: ["立项论证完成（市场/概念/商业模型）", "技术可行性结论明确", "认证/电池安全硬卡完成初判"],
      requiredDeliverables: ["立项申请书"],
      responsibleRoles: ["产品经理", "R&D Lead", "管理层"],
    }),
    tasks: [
      {
        id: "nc1",
        name: "产品机会与立项论证",
        desc: "市场/竞品/用户需求/概念/商业模型，汇为一份立项论证",
        owner: "产品经理",
        evidence: "heavy",
        visibleRoles: ["pm", "sales", "manager", "owner"],
        durationDays: 10,
        guide: "检查项：1) 竞品对比矩阵（TOP3-5） 2) 用户痛点与场景（访谈/问卷规模按项目体量自定） 3) 一句话产品定义+核心卖点 4) 销量/成本/毛利模型。全部落入一份立项申请书。",
      },
      {
        id: "nc2",
        name: "技术可行性评估",
        desc: "关键技术验证、专利检索、认证路线初判",
        owner: "R&D Lead",
        evidence: "heavy",
        visibleRoles: ["rd_hw", "rd_sw", "rd_mech", "cert", "battery_safety", "pm", "manager", "owner"],
        durationDays: 7,
        guide: "1) 关键技术挑战清单与核心 POC 2) 专利检索与规避 3) 目标市场认证路线、电池安全和运输硬卡初判。",
      },
      {
        id: "nc3",
        name: "立项评审 (Gate 1)",
        desc: "正式立项决策评审",
        owner: "管理层",
        visibleRoles: [],
        durationDays: 1,
        dependsOn: ["nc1", "nc2"],
        guide: "评审材料：立项申请书 + 技术可行性结论。通过后在立项配置中完成成员角色指派与排期初始化（原 p3/p6 已移出任务清单）。",
      },
    ],
  },
  {
    id: "planning",
    code: "P2",
    name: "规划阶段",
    nameEn: "Planning",
    duration: "2-3周",
    desc: "需求规格与供应基础",
    gate: "Kickoff评审",
    gateTaskId: "np3",
    color: "#a16207",
    deliverables: ["产品需求文档 PRD", "产品规格书 PSD", "BOM v0.1"],
    gateStandard: gateStandard({
      exitCriteria: ["需求与规格评审通过", "初版 BOM 与关键供应商明确"],
      requiredDeliverables: ["产品需求文档 PRD", "产品规格书 PSD", "BOM v0.1"],
      responsibleRoles: ["产品经理", "R&D", "采购"],
    }),
    tasks: [
      {
        id: "np1",
        name: "产品需求与规格书",
        desc: "PRD/PSD 合一：功能/非功能需求、技术规格、性能与安全边界",
        owner: "产品经理/R&D",
        evidence: "heavy",
        visibleRoles: ["pm", "rd_hw", "rd_sw", "rd_mech", "battery_safety", "manager", "owner"],
        durationDays: 7,
        dependsOn: ["nc3"],
        guide: "检查项：1) 功能需求与验收标准 2) 硬件/软件规格与性能指标 3) 锂电、电机、受压腔体的安全边界与验收指标（必填）。",
      },
      {
        id: "np2",
        name: "初版 BOM 与关键供应商",
        desc: "关键料件清单+供应商列，预估成本",
        owner: "EE/采购",
        evidence: "light",
        visibleRoles: ["rd_hw", "scm", "pm", "manager", "owner"],
        durationDays: 5,
        dependsOn: ["nc3"],
        guide: "一张表：料件/供应商(2-3家)/单价/长交期与单一来源标注；安全件标注资质与替代来源风险。",
      },
      {
        id: "np3",
        name: "Kickoff 会议 (Gate 2)",
        desc: "项目正式启动，目标对齐",
        owner: "项目经理/产品经理",
        visibleRoles: [],
        durationDays: 1,
        dependsOn: ["np1", "np2"],
        guide: "议程：目标/规格 Walk-through/里程碑/角色职责。",
      },
    ],
  },
  {
    id: "design",
    code: "P3",
    name: "设计阶段",
    nameEn: "Design",
    duration: "6-12周",
    desc: "ID/MD/EE 并行设计（独立工作线，不合并）",
    gate: "设计冻结评审 (Design Freeze)",
    gateTaskId: "nd6",
    color: "#0369a1",
    deliverables: ["ID 外观设计稿", "结构 3D 设计", "电子原理图", "PCB Layout 文件", "BOM v1.0"],
    gateStandard: gateStandard({
      exitCriteria: ["ID/MD/EE 设计完成", "DFM/DFA 检查项闭环", "BOM 成本 vs 目标达标", "关键料件规格冻结"],
      requiredDeliverables: ["ID 外观设计稿", "结构 3D 设计", "电子原理图", "PCB Layout 文件", "BOM v1.0"],
      responsibleRoles: ["ID", "MD", "EE", "采购"],
    }),
    tasks: [
      {
        id: "nd1",
        name: "ID 工业设计",
        desc: "外观造型、材质、CMF",
        owner: "ID",
        evidence: "heavy",
        visibleRoles: ["rd_mech", "pm", "manager", "owner"],
        durationDays: 15,
        dependsOn: ["np3"],
        guide: "草图发散→候选精化→CMF 定义→渲染图。外观方向冻结是结构展开前提。",
      },
      {
        id: "nd2",
        name: "MD 结构设计",
        desc: "堆叠、装配、公差",
        owner: "MD",
        evidence: "heavy",
        visibleRoles: ["rd_mech", "pm", "manager", "owner"],
        durationDays: 20,
        dependsOn: ["nd1"],
        guide: "内部堆叠→装配工艺→公差分析。堆叠输出是 Layout 板框前提。",
      },
      {
        id: "nd3",
        name: "EE 原理设计",
        desc: "电源/MCU/传感/保护链路架构与原理图",
        owner: "EE",
        evidence: "heavy",
        visibleRoles: ["rd_hw", "battery_safety", "pm", "manager", "owner"],
        durationDays: 15,
        dependsOn: ["np3"],
        guide: "系统框图→原理图→电源树与功耗；过充/过放/过流/过温/短路保护链路与测试点为必填检查项。",
      },
      {
        id: "nd4",
        name: "PCB Layout",
        desc: "布线、阻抗、EMC",
        owner: "EE",
        evidence: "heavy",
        visibleRoles: ["rd_hw", "pm", "manager", "owner"],
        durationDays: 10,
        dependsOn: ["nd3", "nd2"],
        guide: "板层规划→关键信号阻抗→EMC/EMI→DRC。依赖原理图+结构板框，单独追踪以暴露跨线停等。",
      },
      {
        id: "nd5",
        name: "关键料件定型与 BOM 冻结",
        desc: "主料规格冻结、供货协议、BOM v1.0",
        owner: "EE/采购",
        evidence: "light",
        visibleRoles: ["rd_hw", "scm", "battery_safety", "pm", "manager", "owner"],
        durationDays: 7,
        dependsOn: ["nd3"],
        guide: "2nd Source 验证→供货协议→锁定规格；安全件单独记录批准版本与限制条件。",
      },
      {
        id: "nd6",
        name: "设计冻结评审 (Gate 3)",
        desc: "Design Freeze，进入打样",
        owner: "跨部门",
        visibleRoles: [],
        durationDays: 1,
        dependsOn: ["nd1", "nd2", "nd3", "nd4", "nd5"],
        guide: "评审检查项：1) 各设计线完成度 2) DFM/DFA Checklist（原 d6 转入） 3) BOM 成本 vs 目标 4) EVT 计划。",
      },
    ],
  },
  {
    id: "evt",
    code: "P4",
    name: "EVT 工程验证",
    nameEn: "EVT",
    duration: "4-6周",
    desc: "工程样机功能验证",
    gate: "EVT评审",
    gateTaskId: "ne3",
    color: "#7c3aed",
    deliverables: ["EVT 样机", "功能测试报告 (FT)"],
    gateStandard: gateStandard({
      exitCriteria: ["主要功能 Pass Rate ≥ 95%", "Issue List 无未关闭 P0/P1（系统自动检查）", "性能初测达标"],
      requiredDeliverables: ["功能测试报告 (FT)"],
      responsibleRoles: ["EE", "QA"],
    }),
    tasks: [
      {
        id: "ne1",
        name: "EVT 样机制作",
        desc: "手工样机 ≥10 台（含软硬件联调）",
        owner: "EE/EMS",
        evidence: "light",
        visibleRoles: ["rd_hw", "rd_sw", "pm", "manager", "owner"],
        durationDays: 10,
        dependsOn: ["nd6"],
        guide: "PCBA 打样→整机组装→版本序号标注；软硬件联调（Bringup/驱动/协议）为内部检查项。证据：样机照片+Build Record 链接。",
      },
      {
        id: "ne2",
        name: "EVT 功能/性能测试",
        desc: "FT+PT 一份报告：功能逐项、续航、热、跌落初测",
        owner: "QA",
        evidence: "heavy",
        visibleRoles: ["qa", "rd_hw", "pm", "manager", "owner"],
        durationDays: 10,
        dependsOn: ["ne1"],
        guide: "Test Plan→逐项 Pass/Fail→问题直接进系统 Issue List（原 e5 问题清单任务已删除）；改板由 Issue/ECR 驱动（原 e6）。",
      },
      {
        id: "ne3",
        name: "EVT 评审 (Gate 4)",
        desc: "是否达到进入 DVT 条件",
        owner: "跨部门",
        visibleRoles: [],
        durationDays: 1,
        dependsOn: ["ne2"],
        guide: "P0/P1 关闭状态由系统读 Issue List 自动检查，无需人工汇总问题清单。",
      },
    ],
  },
  {
    id: "dvt",
    code: "P5",
    name: "DVT 设计验证",
    nameEn: "DVT",
    duration: "4-8周",
    desc: "设计成熟度全面验证",
    gate: "DVT评审",
    gateTaskId: "nv3",
    color: "#0f766e",
    deliverables: ["DVT 样机", "可靠性测试报告"],
    gateStandard: gateStandard({
      exitCriteria: ["可靠性测试全部 Pass", "Issue List 无未关闭 P0/P1"],
      requiredDeliverables: ["可靠性测试报告"],
      responsibleRoles: ["EMS", "QA"],
    }),
    tasks: [
      {
        id: "nv1",
        name: "DVT 样机制作",
        desc: "半正式产线 ≥30 台",
        owner: "EMS",
        evidence: "light",
        visibleRoles: ["rd_hw", "pm", "manager", "owner"],
        durationDays: 10,
        dependsOn: ["ne3"],
        guide: "半正式产线 SMT→整机组装→模拟量产工艺。证据：Build Record 链接。",
      },
      {
        id: "nv2",
        name: "可靠性测试",
        desc: "跌落/高低温/湿热/振动/老化",
        owner: "QA",
        evidence: "heavy",
        visibleRoles: ["qa", "pm", "manager", "owner"],
        durationDays: 15,
        dependsOn: ["nv1"],
        guide: "标准矩阵：跌落 1.5m×26 面、-20~60℃、40℃/95%RH×96h、振动。",
      },
      {
        id: "nv3",
        name: "DVT 评审 (Gate 5)",
        desc: "进入 PVT 前的关键评审",
        owner: "跨部门",
        visibleRoles: [],
        durationDays: 1,
        dependsOn: ["nv2"],
        guide: "通过标准：可靠性全 Pass；激活的认证/模具/软件包任务闭环。",
      },
    ],
  },
  {
    id: "pvt",
    code: "P6",
    name: "PVT 试产验证",
    nameEn: "PVT",
    duration: "3-6周",
    desc: "生产工艺与良率验证",
    gate: "MP准备就绪评审",
    gateTaskId: "npv5",
    isReleaseGate: true,
    color: "#b45309",
    deliverables: ["SOP/WI作业指导书", "良率报告", "EOL 100%测试能力验收记录", "包装与物流验证报告"],
    gateStandard: gateStandard({
      exitCriteria: ["试产良率达标（整机直通率≥95%）", "工艺/检验文件完整", "EOL 100% 测试能力就绪", "物料供应稳定"],
      requiredDeliverables: ["SOP/WI作业指导书", "良率报告", "EOL 100%测试能力验收记录", "包装与物流验证报告"],
      responsibleRoles: ["ME", "QA", "测试工程", "SCM"],
    }),
    tasks: [
      {
        id: "npv1",
        name: "试产准备",
        desc: "排程/物料齐套/SOP·WI/检验标准/PFMEA-CTQ 一套文件包",
        owner: "ME/工厂",
        evidence: "heavy",
        visibleRoles: ["rd_mech", "rd_hw", "qa", "scm", "pe", "mfg", "pm", "manager", "owner"],
        durationDays: 10,
        dependsOn: ["nv3"],
        guide: "检查项：试产排程与齐套、每工位 SOP/WI、IPQC/OQC/AQL 检验标准、PFMEA 与 CTQ（原 pv1+pv2+pv7+v7 合一）。",
      },
      {
        id: "npv2",
        name: "治具与 EOL 100% 测试",
        desc: "🚩红线：ATE/FCT/老化治具与逐台安全检测能力",
        owner: "测试工程",
        evidence: "heavy",
        visibleRoles: ["rd_hw", "qa", "pe", "battery_safety", "pm", "manager", "owner"],
        durationDays: 10,
        dependsOn: ["nv3"],
        guide: "逐台检测：气压精度、自动停泵/过压保护、连续工作温升；电池项目叠加 Hi-pot/绝缘/保护功能/OCV-IR。输出限值与验收记录。任何档位不得裁剪。",
      },
      {
        id: "npv3",
        name: "包装与物流验证",
        desc: "包装结构+ISTA 运输测试+装箱物流方案（承接 DVT 初验）",
        owner: "SCM/物流",
        evidence: "heavy",
        visibleRoles: ["scm", "pm", "manager", "owner"],
        durationDays: 7,
        dependsOn: ["nv3"],
        guide: "包装结构确认→ISTA 跌落/振动/堆叠→装箱单唛头→物流路径。同一证据只传一次，Gate 直接引用。",
      },
      {
        id: "npv4",
        name: "试产执行与良率",
        desc: "50-300 台试产 + 良率分析一份报告",
        owner: "工厂/QE",
        evidence: "heavy",
        visibleRoles: ["rd_mech", "rd_hw", "qa", "pe", "mfg", "pm", "manager", "owner"],
        durationDays: 10,
        dependsOn: ["npv1", "npv2"],
        guide: "FAI 首件→全程良率监控（SMT≥99%/组装≥98%/FCT≥97%/直通率≥95% 为检查项）→试产报告含良率分析。",
      },
      {
        id: "npv5",
        name: "PVT 评审 (Gate 6)",
        desc: "🚩红线：量产放行（Ready for MP）",
        owner: "跨部门",
        visibleRoles: [],
        durationDays: 1,
        dependsOn: ["npv1", "npv2", "npv3", "npv4"],
        guide: "量产 GO：良率达标、文件完整、EOL 能力就绪、（电池包激活时）UN38.3/MSDS/安全认证证据齐套、物料稳定。",
      },
    ],
  },
  {
    id: "mp",
    code: "P7",
    name: "量产稳定与移交",
    nameEn: "MP Stabilization & Handover",
    duration: "2-8周",
    desc: "爬坡、稳定性验证与项目关闭移交",
    gate: "项目关闭移交评审",
    gateTaskId: "nm2",
    isCloseGate: true,
    color: "#166534",
    deliverables: ["良率报告"],
    gateStandard: gateStandard({
      exitCriteria: ["首批量产良率稳定", "客户放行完成", "售后/RMA 无未闭环重大问题"],
      requiredDeliverables: [],
      responsibleRoles: ["工厂", "项目经理", "QA"],
    }),
    tasks: [
      {
        id: "nm1",
        name: "首批量产与客户放行",
        desc: "🚩红线：爬坡+良率监控+客户样品确认",
        owner: "工厂/项目经理",
        evidence: "light",
        visibleRoles: ["scm", "qa", "mfg", "pe", "pm", "manager", "owner"],
        durationDays: 15,
        dependsOn: ["npv5"],
        guide: "检查项：首批爬坡、日良率监控与 CAR（原 mp2）、产能爬坡曲线（原 mp3）、客户样品确认与放行记录。变更走系统 Change Log/ECR 模块（原 mp4 已删除）。",
      },
      {
        id: "nm2",
        name: "项目关闭移交评审",
        desc: "Close Gate：移交量产运营",
        owner: "跨部门",
        visibleRoles: [],
        durationDays: 1,
        dependsOn: ["nm1"],
        guide: "检查项：良率稳定证据、RMA/售后数据（原 mp5）、移交清单、经验教训。",
      },
    ],
  },
];
