// 任务交付物模板：每个 SOP 任务预置应产出的交付物名称(可勾选完成、可上传附件)。
// 未配置的任务无预置交付物(不回退到阶段级——阶段级 deliverables 属于 Gate 评审,只在 Gate 任务上展示)。

export const TASK_DELIVERABLES: Record<string, string[]> = {
  // ── NPD ──────────────────────────────────────────────
  c1: ["竞品对比矩阵", "市场调研报告"],
  c2: ["用户访谈纪要", "用户痛点 Top10"],
  c3: ["产品概念书", "用户旅程地图"],
  c4: ["关键技术挑战清单", "核心技术 POC 报告", "专利检索与规避分析", "认证路线图初判"],
  c5: ["销量预测模型", "目标成本与定价分析"],
  c6: ["立项评审记录"],
  p1: ["产品需求文档 PRD"],
  p2: ["产品规格书 PSD"],
  p3: ["WBS 与里程碑计划", "关键路径标注"],
  p4: ["BOM v0.1", "长交期/单一来源料件清单"],
  p5: ["供应商评估表", "样品与报价", "安全件供应商资质清单"],
  p5a: ["电芯复用/定点与二供策略", "电芯规格书与既有认证资料", "电芯供应风险清单"],
  p6a: ["认证路线图", "认证前置依赖与送样计划"],
  p6: ["RACI 责任矩阵"],
  p7: ["Kickoff 会议纪要"],
  d1: ["ID 外观设计稿", "CMF 方案"],
  d2: ["结构 3D 设计", "模具可行性评估"],
  d3: ["电子原理图", "保护电路设计输入"],
  d4: ["PCB Layout 文件"],
  d5: ["软件架构文档"],
  d6: ["DFM/DFA 评审报告"],
  d6a: ["安全FMEA与危害分析", "安全验证项目与判定标准"],
  d7: ["关键料件规格确认", "安全件批准版本记录"],
  d7a: ["电芯厂质量审核或复用资质确认", "电芯供应商整改闭环记录"],
  d7b: ["保护电路设计评审或复用确认", "保护功能测试方案"],
  d8: ["设计冻结评审记录", "BOM v1.0", "安全FMEA与危害分析", "电芯厂质量审核或复用资质确认", "保护电路设计评审或复用确认"],
  e1: ["EVT 样机", "Build Record"],
  e2: ["功能测试报告 (FT)"],
  e3: ["性能测试报告 (PT)"],
  e4: ["软硬件联调报告"],
  e5: ["EVT 问题清单"],
  e6: ["PCB v2 改板记录"],
  e7: ["EVT 评审记录"],
  v1: ["DVT 样机", "Build Record"],
  v2: ["可靠性测试报告"],
  v3: ["安规与认证报告", "UN38.3运输测试报告或复用确认", "MSDS", "电芯/电池包安全认证报告或复用确认"],
  v4: ["模具 T1/T2 试模报告"],
  v5: ["软件功能完整测试报告"],
  v6: ["包装设计验证报告"],
  v7: ["量产工艺评估报告", "PFMEA/CTQ控制计划", "量产测试设备清单"],
  v8: ["DVT 评审记录"],
  pv1: ["试产计划"],
  pv2: ["SOP / WI 文件"],
  pv3: ["治具与测试程序", "EOL 100%测试项目清单", "EOL 100%测试能力验收记录"],
  pv4: ["试产 Build Record", "良率数据"],
  pv5: ["良率分析与改善报告"],
  pv6: ["包装与物流验证报告"],
  pv7: ["限度样本与检验标准", "关键安全/性能检验标准"],
  pv8: ["PVT 评审记录", "EOL 100%测试能力验收记录", "UN38.3运输测试报告或复用确认", "MSDS", "电芯/电池包安全认证报告或复用确认"],
  mp1: ["首批量产 Build Record"],
  mp2: ["良率监控报表"],
  mp3: ["产能爬坡计划"],
  mp4: ["工程变更 ECN 记录"],
  mp5: ["售后问题报表"],
  mp6: ["CIP 持续改善报告"],

  // ── ECO 工程变更 ─────────────────────────────────────
  ep1: ["变更需求单 ECR"],
  ep2: ["影响分析报告"],
  ep3: ["BOM 差异分析"],
  ep4: ["变更时程"],
  ep5: ["资源与供应商确认清单"],
  ep6: ["CCB 变更决策记录"],
  ed1: ["更新后的原理图/PCB", "更新后的BOM"],
  ed2: ["结构变更设计包"],
  ed3: ["软件变更版本说明"],
  ed4: ["DFM 变更评审报告"],
  ed5: ["认证影响评估报告"],
  ed6: ["设计变更冻结记录"],
  ev1: ["变更验证样机"],
  ev2: ["变更点专项验证报告"],
  ev3: ["回归测试报告"],
  ev4: ["变更点可靠性测试报告"],
  ev5: ["变更验证评审记录"],
  epv1: ["更新后的SOP/WI", "产线切换计划"],
  epv2: ["变更试产报告"],
  epv3: ["库存处理方案"],
  epv4: ["ECN 正式发布"],
  em1: ["变更后良率报告"],
  em2: ["变更效果验证报告"],
  em3: ["售后影响跟踪报表"],
  em4: ["ECO 关闭评审记录"],

  // ── DRV project-track-v1 公共任务 ────────────────────
  drv_common_product_baseline: ["产品规格基线确认记录", "六模块执行基线"],
  drv_common_project_plan: ["项目计划与RACI"],
  drv_common_risk_scope: ["风险声明与评估结论"],
  drv_common_kickoff_gate: ["DRV Kickoff评审记录"],
  drv_common_dfm_validation_plan: ["DFM/DFT/DFMEA评审记录", "验证计划"],
  drv_common_accessory_definition: ["配件定义清单"],
  drv_common_design_gate: ["DRV设计冻结评审记录"],
  drv_common_evt_build: ["EVT Build Record"],
  drv_common_system_regression: ["整机功能与兼容性回归报告"],
  drv_common_software_validation: ["软件功能验证报告"],
  drv_common_evt_issue_close: ["EVT问题关闭与DVT输入记录"],
  drv_common_evt_gate: ["DRV EVT评审记录"],
  drv_common_dvt_build: ["DVT Build Record"],
  drv_common_reliability_test: ["可靠性内部测试报告"],
  drv_common_safety_cert_test: [
    "安规与认证验证报告",
    "UN38.3运输测试报告或复用确认",
    "MSDS",
    "电芯/电池包安全认证报告或复用确认",
  ],
  drv_common_accessory_confirm: ["配件确认记录"],
  drv_common_packaging_validation: ["包装验证报告"],
  drv_common_logistics_validation: ["物流验证报告"],
  drv_common_dvt_issue_close: ["DVT问题关闭与PVT Readiness记录"],
  drv_common_dvt_gate: ["DRV DVT评审记录"],
  drv_common_fixture_confirmation: ["治具验收记录"],
  drv_common_eol_program_confirm: [
    "EOL与测试程序验收记录",
    "EOL 100%测试能力验收记录",
  ],
  drv_common_pvt_trial: ["PVT试产报告"],
  drv_common_pvt_quality_close: ["试产良率与问题关闭报告"],
  drv_common_release_files: [
    "产品文件BOM与量产交付清单",
    "认证与运输证据覆盖复核记录",
  ],
  drv_common_pvt_release_gate: ["DRV量产发布评审记录"],

  // ── DRV project-track-v1 六模块任务包 ────────────────
  drv_battery_design: ["电池/能源系统设计包"],
  drv_battery_sample_integration: ["电池模块样件与集成记录"],
  drv_battery_special_validation: ["电池性能与保护专项验证报告"],
  drv_core_function_design: ["核心功能部件设计包"],
  drv_core_function_sample: ["核心功能部件样件记录"],
  drv_core_special_validation: ["核心功能部件专项验证报告"],
  drv_electronics_design: ["电子硬件设计包"],
  drv_electronics_sample_build: ["电子硬件样件联调记录"],
  drv_electronics_special_test: ["电子硬件专项验证报告"],
  drv_software_requirements_design: ["软件/连接需求与设计包"],
  drv_software_dev_integration: ["软件开发联调记录"],
  drv_software_special_validation: ["软件接口与异常专项验证报告"],
  drv_structure_design: ["产品结构设计包"],
  drv_structure_mold_review: ["投模评审与开模批准记录"],
  drv_structure_mold_development: ["模具开发计划"],
  drv_structure_t1_t2_validation: ["T1/T2 与结构专项验证报告"],
  drv_id_cmf_design: ["ID/CMF 设计包"],
  drv_id_cmf_sample: ["颜色/材质/工艺样件"],
  drv_id_cmf_standard_confirmation: ["外观标准与限度样本"],

  // ── 通用发布后稳定与关闭 ─────────────────────────────
  stability_ramp: ["首批量产与爬坡记录"],
  stability_metrics: ["稳定期周报与QA结论"],
  stability_issues: ["遗留问题关闭与受控转交记录"],
  project_close_review: ["项目关闭评审记录"],

  // ── JDM project-track-v1 定义基线与客户确认 ───────────
  jdm_input_snapshot: ["产品概念书"],
  jdm_requirements_gap: ["问题清单"],
  jdm_product_spec: ["产品规格书 PSD"],
  jdm_csr: ["客户特殊要求清单 CSR"],
  jdm_boundary_raci: ["RACI 责任矩阵"],
  jdm_module_reuse_draft: ["六模块执行基线"],
  jdm_product_owner_approval: ["产品规格基线确认记录"],
  jdm_customer_spec_csr_confirm: ["规格确认书（客户签字）"],
  jdm_product_definition_gate: ["设计输入冻结确认（客户）"],
  jdm_customer_design_confirm: ["客户外观签核记录"],
  jdm_customer_evt_confirm: ["客户样机确认记录"],
  jdm_customer_dvt_confirm: ["客户 DVT 确认记录"],
  jdm_customer_golden_confirm: ["客户 golden sample 签样记录"],
  jdm_customer_release_confirm: ["客户放行记录"],

  // ── IDR 外观翻新 ─────────────────────────────────────
  ir1: ["翻新需求与边界定义"],
  ir2: ["现有设计基线包"],
  ir3: ["影响分析矩阵"],
  ir4: ["BOM差异与新物料清单"],
  ir5: ["认证路径预判"],
  ir6: ["IDR Kickoff 记录"],
  id1: ["ID/CMF设计包"],
  id2: ["MD结构图纸"],
  id3: ["硬件影响确认"],
  id4: ["包装/标签设计稿"],
  id5: ["BOM/图纸/ECN 草案"],
  id6: ["供应商样件"],
  id7: ["设计冻结评审记录"],
  iv1: ["验证样机"],
  iv2: ["结构与装配验证报告"],
  iv3: ["功能与性能回归测试报告"],
  iv4: ["可靠性与外观耐久测试报告", "包装验证报告"],
  iv5: ["认证更新/重认证报告"],
  iv6: ["外观检验标准"],
  iv7: ["验证与认证评审记录"],
  im1: ["SOP/WI更新记录"],
  im2: ["PVT或首批质量报告"],
  im3: ["版本切换计划"],
  im4: ["文件与认证资料发布记录"],
  im5: ["市场上市计划"],
  im6: ["MP Release 评审记录"],


  // ── OBT 转产导入 ──────────────────────────────────────
  or1: ["openBOM 核对清单"],
  or2: ["图纸/规格完整性确认"],
  or3: ["DFM/可制造性反馈报告"],
  or4: ["料件齐套与替代料策略"],
  or5: ["模具/治具归属与 NRE 确认"],
  or6: ["报价"],
  or7: ["模具/治具归属与 NRE 确认", "设计输入冻结确认（客户）"],
  os1: ["首件样品"],
  os2: ["FAI 首件检验报告"],
  os3: ["测试程序与治具"],
  os4: ["客户样品确认记录"],
  os5: ["FAI 首件检验报告", "客户签样记录"],
  op1: ["小批试产报告"],
  op2: ["良率分析与改善报告"],
  op3: ["SOP/WI"],
  op4: ["包装与物流验证报告", "UN38.3运输测试报告或复用确认", "MSDS"],
  op5: ["MP 准备就绪评审记录", "客户放行记录"],
  om1: ["首批量产 Build Record"],
  om2: ["良率周报"],
  om3: ["售后问题报表"],
  om4: ["产品交付/EOL 评审记录"],

  // ── NPD v3（2026-07-v3，瘦身分档版）──────────────────
  nc1: ["立项申请书"],
  nc2: ["关键技术挑战清单", "核心技术 POC 报告", "专利检索与规避分析", "认证路线图初判"],
  np1: ["产品需求文档 PRD"],
  np2: ["BOM v0.1"],
  nd1: ["ID 外观设计稿", "CMF 方案"],
  nd2: ["结构 3D 设计", "模具可行性评估"],
  nd3: ["电子原理图", "保护电路设计输入"],
  nd4: ["PCB Layout 文件"],
  nd5: ["关键料件规格确认", "安全件批准版本记录", "BOM v1.0"],
  ne1: ["EVT 样机", "Build Record"],
  ne2: ["功能/性能测试报告"],
  nv1: ["DVT 样机", "Build Record"],
  nv2: ["可靠性测试报告"],
  npv1: ["SOP/WI作业指导书", "PFMEA/CTQ控制计划"],
  npv2: ["EOL 100%测试能力验收记录", "治具与测试程序"],
  npv3: ["包装与物流验证报告"],
  npv4: ["良率报告"],
  nm1: ["良率报告"],

  // 轻量档合并任务使用独立 id，避免按 taskId 查询时污染标准档。
  nlc1: ["立项申请书"],
  nlp1: ["产品需求文档 PRD", "BOM v0.1"],
  nld3: ["EE 原理图 & PCB Layout"],
  nle1: ["Build Record", "功能/性能测试报告"],
  nlpv1: ["SOP/WI作业指导书", "包装与物流验证报告", "良率报告"],

  // 按项目属性激活的附加包任务。
  pb1: ["电芯复用/定点与二供策略", "电芯厂质量审核或复用资质确认"],
  pb2: ["安全FMEA与危害分析", "保护电路设计评审或复用确认"],
  pc1: ["认证路线图", "认证前置依赖与送样计划"],
  pc2: ["认证报告"],
  ps1: ["软件架构文档"],
  ps2: ["软件完整测试报告"],
  pmo1: ["模具T1样品", "模具 T1/T2 试模报告"],
};

/** 取任务的交付物模板；未配置则为空(阶段级 deliverables 只在 Gate 任务上展示) */
export function getTaskDeliverables(taskId: string): string[] {
  return TASK_DELIVERABLES[taskId] ?? [];
}
